### ISSUE TITLE
Is it fully functional ?

### ISSUE THREAD

**Issue by ishmam999** [niyazed/wordify#2]
Chole naki ?

**Comment by niyazed** [comment]
Ha chole, tobe pdf upload dis na, ota prblmOn Feb 14, 2020 8:26 AM, Ishmam Islam <notifications@github.com> wrote:Chole naki ?

**Comment by niyazed** [comment]
Image, text, docx file working....shudu pdf problem

**Comment by niyazed** [comment]
pdf issue fixed
